version: '2'
services:
    django:
        build: ./django
        command: uwsgi --ini uwsgi.ini --py-autoreload 1
        container_name: django
        environment:
            - DJ_ENV=$DJ_ENV
            - DJ_DB_NAME=$DJ_DB_NAME
            - DJ_DB_USER=$DJ_DB_USER
            - DJ_DB_PASSWORD=$DJ_DB_PASSWORD
            - DJ_DB_HOST=$DJ_DB_HOST
            - DJ_DB_PORT=$DJ_DB_PORT
            - DJ_SECRET_KEY=$DJ_SECRET_KEY
            - DJ_SOCIAL_AUTH_FACEBOOK_KEY=$DJ_SOCIAL_AUTH_FACEBOOK_KEY
            - DJ_SOCIAL_AUTH_FACEBOOK_SECRET=$DJ_SOCIAL_AUTH_FACEBOOK_SECRET
        expose:
            - 8000
        restart: always
        volumes:
            - ./django:/home/django
    nginx:
        build: ./nginx
        container_name: nginx
        depends_on:
            - django
        ports:
            - 80:80
        restart: always
        volumes_from:
            - django
