version: '2'
services:
    api:
        build: ./api
        command: uwsgi --ini uwsgi.ini --py-autoreload 1
        container_name: api
        environment:
            - DJ_ENV=$DJ_ENV
            - DJ_DB_NAME=$DJ_DB_NAME
            - DJ_DB_USER=$DJ_DB_USER
            - DJ_DB_PASSWORD=$DJ_DB_PASSWORD
            - DJ_DB_HOST=$DJ_DB_HOST
            - DJ_DB_PORT=$DJ_DB_PORT
            - DJ_SECRET_KEY=$DJ_SECRET_KEY
            - DJ_SOCIAL_AUTH_FACEBOOK_KEY=$DJ_SOCIAL_AUTH_FACEBOOK_KEY
            - DJ_SOCIAL_AUTH_FACEBOOK_SECRET=$DJ_SOCIAL_AUTH_FACEBOOK_SECRET
        expose:
            - 8000
        restart: always
        volumes:
            - ./api:/home/api
    web:
        build: ./web
        command: uwsgi --ini uwsgi.ini --py-autoreload 1
        container_name: web
        environment:
            - FLASK_APP=$FLASK_APP
        expose:
            - 5000
        restart: always
        volumes:
            - ./web:/home/web
    nginx:
        build: ./nginx
        container_name: nginx
        depends_on:
            - api
            - web
        ports:
            - 80:80
            - 9055:9055
        restart: always
        volumes_from:
            - api
            - web
